### ISSUE TITLE
Send PR to Immutable.js

### ISSUE THREAD

**Issue by BLamy** [applitopia/immutable-sorted#11] opened 2019-07-09 03:04 UTC
It seems like Lee Bryon was open to adding SortedMap and SortedSet to the main immutable.js package. I'm wondering why you guy have chosen to maintain a fork instead of merging into the main repo.

https://github.com/immutable-js/immutable-js/issues/88#issuecomment-334308337

**Comment by applitopia** [comment] 2019-07-09 07:31
Hi at that time facebook required some paperwork to be signed to have your PR accepted. We didn't have time to properly review that document nor we didn't get to check with our lawyer.

**Comment by CMCDragonkai** [comment] 2019-08-27 04:31
I was wondering if this is an "extension" why not have it as a plugin, or peer dependency rather than be a complete fork of immutable...

**Comment by applitopia** [comment] 2019-10-10 02:49
Closing as it looks like a duplicate of issue #1

**Closed as completed by applitopia** 2019-10-10 02:49 UTC
Labels: duplicate
